### PR TITLE
Add isort for python import sorting

### PR DESCRIPTION
**Pull request by TamaMcGlinn**

### CODE REVIEW

**Comment by dbarnett** [comment]
Could you sign the Contributor License Agreement at https://cla.developers.google.com/? Sorry for the extra step, but Google wants to make sure all the legal risks are covered.

**Comment by TamaMcGlinn** [comment]
Done, please rescan.

**Comment by dbarnett** [comment]
Thanks, good now! Will review changes in a bit.

**Review by dbarnett — APPROVED** [review]

**Comment by TruncatedDinosour** [comment]
I shouldn't have closed my PR lmao

**Comment by TamaMcGlinn** [comment]
I had not even seen it. Yours even has unit tests! I wonder whether your tests work with my implementation.

**Comment by TruncatedDinosour** [comment]
> 



> I had not even seen it. Yours even has unit tests! I wonder whether your tests work with my implementation.

I have no idea, have not tested them, just went off the `black` implementation :)

**Pull request merged**
