### PR TITLE
Enable clang-format on C files.

### PR DESCRIPTION
**Pull request by rickyz**

### CODE REVIEW

**Comment by rickyz** [comment]
I've recommitted the change under my google.com email, which should have the appropriate CLA bits.

**Comment by dbarnett** [comment]
Can you also update the lists of filetypes in the docs?
  * autoload/codefmt.vim (and regenerate with vimdoc)
  * vroom/clangformat.vroom

**Comment by fowles** [comment]
I verified that rickyz is who he claims to be.

**Comment by rickyz** [comment]
@dbarnett Oops, I updated the docs, thanks!

**Comment by dbarnett** [comment]
LGTM.

**Pull request merged**
